### PR TITLE
Update curl.md with instructions for replicating packages via cURL

### PR DESCRIPTION
**Pull request by jlanssie**
Added instructions on how to replicate / activate / publish a package via cURL.

### CODE REVIEW

**Comment by aheim0** [comment]
Thank you for the contribution. 
However, AEM 6.4 has reached the end of life and we are no longer accepting contributions to its docs. We are looking for a solution to remove the contribution links to the docs in these circumstances.

**Comment by jlanssie** [comment]
My addition also applies to aem 6.5
Can you add it there?

**Comment by aheim0** [comment]
@adobe export issue to Jira project CQDOC

**Comment by aheim0** [comment]
Yes, we can do that.

Tracked with CQDOC-19636 - for changes to 6.5.

**Comment by aheim0** [comment]
The changes have been applied to the 6.5 docs - they will be published soon.

Thanks for your suggestions.

**Pull request closed without merging**
